// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gopilosa_pbuf/public.proto

package gopilosa_pbuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Row struct {
	Columns              []uint64 `protobuf:"varint,1,rep,packed,name=Columns,proto3" json:"Columns,omitempty"`
	Keys                 []string `protobuf:"bytes,3,rep,name=Keys,proto3" json:"Keys,omitempty"`
	Attrs                []*Attr  `protobuf:"bytes,2,rep,name=Attrs,proto3" json:"Attrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{0}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetColumns() []uint64 {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Row) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Row) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type RowIdentifiers struct {
	Rows                 []uint64 `protobuf:"varint,1,rep,packed,name=Rows,proto3" json:"Rows,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=Keys,proto3" json:"Keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RowIdentifiers) Reset()         { *m = RowIdentifiers{} }
func (m *RowIdentifiers) String() string { return proto.CompactTextString(m) }
func (*RowIdentifiers) ProtoMessage()    {}
func (*RowIdentifiers) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{1}
}

func (m *RowIdentifiers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowIdentifiers.Unmarshal(m, b)
}
func (m *RowIdentifiers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowIdentifiers.Marshal(b, m, deterministic)
}
func (m *RowIdentifiers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowIdentifiers.Merge(m, src)
}
func (m *RowIdentifiers) XXX_Size() int {
	return xxx_messageInfo_RowIdentifiers.Size(m)
}
func (m *RowIdentifiers) XXX_DiscardUnknown() {
	xxx_messageInfo_RowIdentifiers.DiscardUnknown(m)
}

var xxx_messageInfo_RowIdentifiers proto.InternalMessageInfo

func (m *RowIdentifiers) GetRows() []uint64 {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *RowIdentifiers) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Pair struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{2}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type FieldRow struct {
	Field                string   `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	RowID                uint64   `protobuf:"varint,2,opt,name=RowID,proto3" json:"RowID,omitempty"`
	RowKey               string   `protobuf:"bytes,3,opt,name=RowKey,proto3" json:"RowKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldRow) Reset()         { *m = FieldRow{} }
func (m *FieldRow) String() string { return proto.CompactTextString(m) }
func (*FieldRow) ProtoMessage()    {}
func (*FieldRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{3}
}

func (m *FieldRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldRow.Unmarshal(m, b)
}
func (m *FieldRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldRow.Marshal(b, m, deterministic)
}
func (m *FieldRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldRow.Merge(m, src)
}
func (m *FieldRow) XXX_Size() int {
	return xxx_messageInfo_FieldRow.Size(m)
}
func (m *FieldRow) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldRow.DiscardUnknown(m)
}

var xxx_messageInfo_FieldRow proto.InternalMessageInfo

func (m *FieldRow) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *FieldRow) GetRowID() uint64 {
	if m != nil {
		return m.RowID
	}
	return 0
}

func (m *FieldRow) GetRowKey() string {
	if m != nil {
		return m.RowKey
	}
	return ""
}

type GroupCount struct {
	Group                []*FieldRow `protobuf:"bytes,1,rep,name=Group,proto3" json:"Group,omitempty"`
	Count                uint64      `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GroupCount) Reset()         { *m = GroupCount{} }
func (m *GroupCount) String() string { return proto.CompactTextString(m) }
func (*GroupCount) ProtoMessage()    {}
func (*GroupCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{4}
}

func (m *GroupCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupCount.Unmarshal(m, b)
}
func (m *GroupCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupCount.Marshal(b, m, deterministic)
}
func (m *GroupCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupCount.Merge(m, src)
}
func (m *GroupCount) XXX_Size() int {
	return xxx_messageInfo_GroupCount.Size(m)
}
func (m *GroupCount) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupCount.DiscardUnknown(m)
}

var xxx_messageInfo_GroupCount proto.InternalMessageInfo

func (m *GroupCount) GetGroup() []*FieldRow {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *GroupCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ValCount struct {
	Val                  int64    `protobuf:"varint,1,opt,name=Val,proto3" json:"Val,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValCount) Reset()         { *m = ValCount{} }
func (m *ValCount) String() string { return proto.CompactTextString(m) }
func (*ValCount) ProtoMessage()    {}
func (*ValCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{5}
}

func (m *ValCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValCount.Unmarshal(m, b)
}
func (m *ValCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValCount.Marshal(b, m, deterministic)
}
func (m *ValCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValCount.Merge(m, src)
}
func (m *ValCount) XXX_Size() int {
	return xxx_messageInfo_ValCount.Size(m)
}
func (m *ValCount) XXX_DiscardUnknown() {
	xxx_messageInfo_ValCount.DiscardUnknown(m)
}

var xxx_messageInfo_ValCount proto.InternalMessageInfo

func (m *ValCount) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *ValCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ColumnAttrSet struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	Attrs                []*Attr  `protobuf:"bytes,2,rep,name=Attrs,proto3" json:"Attrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnAttrSet) Reset()         { *m = ColumnAttrSet{} }
func (m *ColumnAttrSet) String() string { return proto.CompactTextString(m) }
func (*ColumnAttrSet) ProtoMessage()    {}
func (*ColumnAttrSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{6}
}

func (m *ColumnAttrSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnAttrSet.Unmarshal(m, b)
}
func (m *ColumnAttrSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnAttrSet.Marshal(b, m, deterministic)
}
func (m *ColumnAttrSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnAttrSet.Merge(m, src)
}
func (m *ColumnAttrSet) XXX_Size() int {
	return xxx_messageInfo_ColumnAttrSet.Size(m)
}
func (m *ColumnAttrSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnAttrSet.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnAttrSet proto.InternalMessageInfo

func (m *ColumnAttrSet) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ColumnAttrSet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ColumnAttrSet) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type Attr struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Type                 uint64   `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	StringValue          string   `protobuf:"bytes,3,opt,name=StringValue,proto3" json:"StringValue,omitempty"`
	IntValue             int64    `protobuf:"varint,4,opt,name=IntValue,proto3" json:"IntValue,omitempty"`
	BoolValue            bool     `protobuf:"varint,5,opt,name=BoolValue,proto3" json:"BoolValue,omitempty"`
	FloatValue           float64  `protobuf:"fixed64,6,opt,name=FloatValue,proto3" json:"FloatValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attr) Reset()         { *m = Attr{} }
func (m *Attr) String() string { return proto.CompactTextString(m) }
func (*Attr) ProtoMessage()    {}
func (*Attr) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{7}
}

func (m *Attr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attr.Unmarshal(m, b)
}
func (m *Attr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attr.Marshal(b, m, deterministic)
}
func (m *Attr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attr.Merge(m, src)
}
func (m *Attr) XXX_Size() int {
	return xxx_messageInfo_Attr.Size(m)
}
func (m *Attr) XXX_DiscardUnknown() {
	xxx_messageInfo_Attr.DiscardUnknown(m)
}

var xxx_messageInfo_Attr proto.InternalMessageInfo

func (m *Attr) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Attr) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Attr) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *Attr) GetIntValue() int64 {
	if m != nil {
		return m.IntValue
	}
	return 0
}

func (m *Attr) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *Attr) GetFloatValue() float64 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

type AttrMap struct {
	Attrs                []*Attr  `protobuf:"bytes,1,rep,name=Attrs,proto3" json:"Attrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttrMap) Reset()         { *m = AttrMap{} }
func (m *AttrMap) String() string { return proto.CompactTextString(m) }
func (*AttrMap) ProtoMessage()    {}
func (*AttrMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{8}
}

func (m *AttrMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttrMap.Unmarshal(m, b)
}
func (m *AttrMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttrMap.Marshal(b, m, deterministic)
}
func (m *AttrMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttrMap.Merge(m, src)
}
func (m *AttrMap) XXX_Size() int {
	return xxx_messageInfo_AttrMap.Size(m)
}
func (m *AttrMap) XXX_DiscardUnknown() {
	xxx_messageInfo_AttrMap.DiscardUnknown(m)
}

var xxx_messageInfo_AttrMap proto.InternalMessageInfo

func (m *AttrMap) GetAttrs() []*Attr {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type QueryRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
	Shards               []uint64 `protobuf:"varint,2,rep,packed,name=Shards,proto3" json:"Shards,omitempty"`
	ColumnAttrs          bool     `protobuf:"varint,3,opt,name=ColumnAttrs,proto3" json:"ColumnAttrs,omitempty"`
	Remote               bool     `protobuf:"varint,5,opt,name=Remote,proto3" json:"Remote,omitempty"`
	ExcludeRowAttrs      bool     `protobuf:"varint,6,opt,name=ExcludeRowAttrs,proto3" json:"ExcludeRowAttrs,omitempty"`
	ExcludeColumns       bool     `protobuf:"varint,7,opt,name=ExcludeColumns,proto3" json:"ExcludeColumns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{9}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *QueryRequest) GetShards() []uint64 {
	if m != nil {
		return m.Shards
	}
	return nil
}

func (m *QueryRequest) GetColumnAttrs() bool {
	if m != nil {
		return m.ColumnAttrs
	}
	return false
}

func (m *QueryRequest) GetRemote() bool {
	if m != nil {
		return m.Remote
	}
	return false
}

func (m *QueryRequest) GetExcludeRowAttrs() bool {
	if m != nil {
		return m.ExcludeRowAttrs
	}
	return false
}

func (m *QueryRequest) GetExcludeColumns() bool {
	if m != nil {
		return m.ExcludeColumns
	}
	return false
}

type QueryResponse struct {
	Err                  string           `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	Results              []*QueryResult   `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
	ColumnAttrSets       []*ColumnAttrSet `protobuf:"bytes,3,rep,name=ColumnAttrSets,proto3" json:"ColumnAttrSets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{10}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *QueryResponse) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetColumnAttrSets() []*ColumnAttrSet {
	if m != nil {
		return m.ColumnAttrSets
	}
	return nil
}

type QueryResult struct {
	Type                 uint32          `protobuf:"varint,6,opt,name=Type,proto3" json:"Type,omitempty"`
	Row                  *Row            `protobuf:"bytes,1,opt,name=Row,proto3" json:"Row,omitempty"`
	N                    uint64          `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	Pairs                []*Pair         `protobuf:"bytes,3,rep,name=Pairs,proto3" json:"Pairs,omitempty"`
	Changed              bool            `protobuf:"varint,4,opt,name=Changed,proto3" json:"Changed,omitempty"`
	ValCount             *ValCount       `protobuf:"bytes,5,opt,name=ValCount,proto3" json:"ValCount,omitempty"`
	RowIDs               []uint64        `protobuf:"varint,7,rep,packed,name=RowIDs,proto3" json:"RowIDs,omitempty"`
	GroupCounts          []*GroupCount   `protobuf:"bytes,8,rep,name=GroupCounts,proto3" json:"GroupCounts,omitempty"`
	RowIdentifiers       *RowIdentifiers `protobuf:"bytes,9,opt,name=RowIdentifiers,proto3" json:"RowIdentifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryResult) Reset()         { *m = QueryResult{} }
func (m *QueryResult) String() string { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()    {}
func (*QueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{11}
}

func (m *QueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResult.Unmarshal(m, b)
}
func (m *QueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResult.Marshal(b, m, deterministic)
}
func (m *QueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResult.Merge(m, src)
}
func (m *QueryResult) XXX_Size() int {
	return xxx_messageInfo_QueryResult.Size(m)
}
func (m *QueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResult proto.InternalMessageInfo

func (m *QueryResult) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *QueryResult) GetRow() *Row {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *QueryResult) GetN() uint64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *QueryResult) GetPairs() []*Pair {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *QueryResult) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

func (m *QueryResult) GetValCount() *ValCount {
	if m != nil {
		return m.ValCount
	}
	return nil
}

func (m *QueryResult) GetRowIDs() []uint64 {
	if m != nil {
		return m.RowIDs
	}
	return nil
}

func (m *QueryResult) GetGroupCounts() []*GroupCount {
	if m != nil {
		return m.GroupCounts
	}
	return nil
}

func (m *QueryResult) GetRowIdentifiers() *RowIdentifiers {
	if m != nil {
		return m.RowIdentifiers
	}
	return nil
}

type ImportRequest struct {
	Index                string   `protobuf:"bytes,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
	Shard                uint64   `protobuf:"varint,3,opt,name=Shard,proto3" json:"Shard,omitempty"`
	RowIDs               []uint64 `protobuf:"varint,4,rep,packed,name=RowIDs,proto3" json:"RowIDs,omitempty"`
	ColumnIDs            []uint64 `protobuf:"varint,5,rep,packed,name=ColumnIDs,proto3" json:"ColumnIDs,omitempty"`
	RowKeys              []string `protobuf:"bytes,7,rep,name=RowKeys,proto3" json:"RowKeys,omitempty"`
	ColumnKeys           []string `protobuf:"bytes,8,rep,name=ColumnKeys,proto3" json:"ColumnKeys,omitempty"`
	Timestamps           []int64  `protobuf:"varint,6,rep,packed,name=Timestamps,proto3" json:"Timestamps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportRequest) Reset()         { *m = ImportRequest{} }
func (m *ImportRequest) String() string { return proto.CompactTextString(m) }
func (*ImportRequest) ProtoMessage()    {}
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{12}
}

func (m *ImportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRequest.Unmarshal(m, b)
}
func (m *ImportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRequest.Marshal(b, m, deterministic)
}
func (m *ImportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRequest.Merge(m, src)
}
func (m *ImportRequest) XXX_Size() int {
	return xxx_messageInfo_ImportRequest.Size(m)
}
func (m *ImportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRequest proto.InternalMessageInfo

func (m *ImportRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ImportRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ImportRequest) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *ImportRequest) GetRowIDs() []uint64 {
	if m != nil {
		return m.RowIDs
	}
	return nil
}

func (m *ImportRequest) GetColumnIDs() []uint64 {
	if m != nil {
		return m.ColumnIDs
	}
	return nil
}

func (m *ImportRequest) GetRowKeys() []string {
	if m != nil {
		return m.RowKeys
	}
	return nil
}

func (m *ImportRequest) GetColumnKeys() []string {
	if m != nil {
		return m.ColumnKeys
	}
	return nil
}

func (m *ImportRequest) GetTimestamps() []int64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

type ImportValueRequest struct {
	Index                string   `protobuf:"bytes,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
	Shard                uint64   `protobuf:"varint,3,opt,name=Shard,proto3" json:"Shard,omitempty"`
	ColumnIDs            []uint64 `protobuf:"varint,5,rep,packed,name=ColumnIDs,proto3" json:"ColumnIDs,omitempty"`
	ColumnKeys           []string `protobuf:"bytes,7,rep,name=ColumnKeys,proto3" json:"ColumnKeys,omitempty"`
	Values               []int64  `protobuf:"varint,6,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportValueRequest) Reset()         { *m = ImportValueRequest{} }
func (m *ImportValueRequest) String() string { return proto.CompactTextString(m) }
func (*ImportValueRequest) ProtoMessage()    {}
func (*ImportValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{13}
}

func (m *ImportValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportValueRequest.Unmarshal(m, b)
}
func (m *ImportValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportValueRequest.Marshal(b, m, deterministic)
}
func (m *ImportValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportValueRequest.Merge(m, src)
}
func (m *ImportValueRequest) XXX_Size() int {
	return xxx_messageInfo_ImportValueRequest.Size(m)
}
func (m *ImportValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportValueRequest proto.InternalMessageInfo

func (m *ImportValueRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ImportValueRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ImportValueRequest) GetShard() uint64 {
	if m != nil {
		return m.Shard
	}
	return 0
}

func (m *ImportValueRequest) GetColumnIDs() []uint64 {
	if m != nil {
		return m.ColumnIDs
	}
	return nil
}

func (m *ImportValueRequest) GetColumnKeys() []string {
	if m != nil {
		return m.ColumnKeys
	}
	return nil
}

func (m *ImportValueRequest) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type TranslateKeysRequest struct {
	Index                string   `protobuf:"bytes,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"`
	Keys                 []string `protobuf:"bytes,3,rep,name=Keys,proto3" json:"Keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateKeysRequest) Reset()         { *m = TranslateKeysRequest{} }
func (m *TranslateKeysRequest) String() string { return proto.CompactTextString(m) }
func (*TranslateKeysRequest) ProtoMessage()    {}
func (*TranslateKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{14}
}

func (m *TranslateKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateKeysRequest.Unmarshal(m, b)
}
func (m *TranslateKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateKeysRequest.Marshal(b, m, deterministic)
}
func (m *TranslateKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateKeysRequest.Merge(m, src)
}
func (m *TranslateKeysRequest) XXX_Size() int {
	return xxx_messageInfo_TranslateKeysRequest.Size(m)
}
func (m *TranslateKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateKeysRequest proto.InternalMessageInfo

func (m *TranslateKeysRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *TranslateKeysRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *TranslateKeysRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type TranslateKeysResponse struct {
	IDs                  []uint64 `protobuf:"varint,3,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateKeysResponse) Reset()         { *m = TranslateKeysResponse{} }
func (m *TranslateKeysResponse) String() string { return proto.CompactTextString(m) }
func (*TranslateKeysResponse) ProtoMessage()    {}
func (*TranslateKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{15}
}

func (m *TranslateKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateKeysResponse.Unmarshal(m, b)
}
func (m *TranslateKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateKeysResponse.Marshal(b, m, deterministic)
}
func (m *TranslateKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateKeysResponse.Merge(m, src)
}
func (m *TranslateKeysResponse) XXX_Size() int {
	return xxx_messageInfo_TranslateKeysResponse.Size(m)
}
func (m *TranslateKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateKeysResponse proto.InternalMessageInfo

func (m *TranslateKeysResponse) GetIDs() []uint64 {
	if m != nil {
		return m.IDs
	}
	return nil
}

type ImportRoaringRequestView struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportRoaringRequestView) Reset()         { *m = ImportRoaringRequestView{} }
func (m *ImportRoaringRequestView) String() string { return proto.CompactTextString(m) }
func (*ImportRoaringRequestView) ProtoMessage()    {}
func (*ImportRoaringRequestView) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{16}
}

func (m *ImportRoaringRequestView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRoaringRequestView.Unmarshal(m, b)
}
func (m *ImportRoaringRequestView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRoaringRequestView.Marshal(b, m, deterministic)
}
func (m *ImportRoaringRequestView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRoaringRequestView.Merge(m, src)
}
func (m *ImportRoaringRequestView) XXX_Size() int {
	return xxx_messageInfo_ImportRoaringRequestView.Size(m)
}
func (m *ImportRoaringRequestView) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRoaringRequestView.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRoaringRequestView proto.InternalMessageInfo

func (m *ImportRoaringRequestView) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImportRoaringRequestView) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ImportRoaringRequest struct {
	Clear                bool                        `protobuf:"varint,1,opt,name=Clear,proto3" json:"Clear,omitempty"`
	Views                []*ImportRoaringRequestView `protobuf:"bytes,2,rep,name=views,proto3" json:"views,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ImportRoaringRequest) Reset()         { *m = ImportRoaringRequest{} }
func (m *ImportRoaringRequest) String() string { return proto.CompactTextString(m) }
func (*ImportRoaringRequest) ProtoMessage()    {}
func (*ImportRoaringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{17}
}

func (m *ImportRoaringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportRoaringRequest.Unmarshal(m, b)
}
func (m *ImportRoaringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportRoaringRequest.Marshal(b, m, deterministic)
}
func (m *ImportRoaringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportRoaringRequest.Merge(m, src)
}
func (m *ImportRoaringRequest) XXX_Size() int {
	return xxx_messageInfo_ImportRoaringRequest.Size(m)
}
func (m *ImportRoaringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportRoaringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportRoaringRequest proto.InternalMessageInfo

func (m *ImportRoaringRequest) GetClear() bool {
	if m != nil {
		return m.Clear
	}
	return false
}

func (m *ImportRoaringRequest) GetViews() []*ImportRoaringRequestView {
	if m != nil {
		return m.Views
	}
	return nil
}

type QueryPQLRequest struct {
	Index                string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Pql                  string   `protobuf:"bytes,2,opt,name=pql,proto3" json:"pql,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPQLRequest) Reset()         { *m = QueryPQLRequest{} }
func (m *QueryPQLRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPQLRequest) ProtoMessage()    {}
func (*QueryPQLRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{18}
}

func (m *QueryPQLRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPQLRequest.Unmarshal(m, b)
}
func (m *QueryPQLRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPQLRequest.Marshal(b, m, deterministic)
}
func (m *QueryPQLRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPQLRequest.Merge(m, src)
}
func (m *QueryPQLRequest) XXX_Size() int {
	return xxx_messageInfo_QueryPQLRequest.Size(m)
}
func (m *QueryPQLRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPQLRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPQLRequest proto.InternalMessageInfo

func (m *QueryPQLRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *QueryPQLRequest) GetPql() string {
	if m != nil {
		return m.Pql
	}
	return ""
}

type RowResponse struct {
	ColumnInfo           []*ColumnInfo     `protobuf:"bytes,1,rep,name=column_info,json=columnInfo,proto3" json:"column_info,omitempty"`
	Columns              []*ColumnResponse `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RowResponse) Reset()         { *m = RowResponse{} }
func (m *RowResponse) String() string { return proto.CompactTextString(m) }
func (*RowResponse) ProtoMessage()    {}
func (*RowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{19}
}

func (m *RowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowResponse.Unmarshal(m, b)
}
func (m *RowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowResponse.Marshal(b, m, deterministic)
}
func (m *RowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowResponse.Merge(m, src)
}
func (m *RowResponse) XXX_Size() int {
	return xxx_messageInfo_RowResponse.Size(m)
}
func (m *RowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RowResponse proto.InternalMessageInfo

func (m *RowResponse) GetColumnInfo() []*ColumnInfo {
	if m != nil {
		return m.ColumnInfo
	}
	return nil
}

func (m *RowResponse) GetColumns() []*ColumnResponse {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ColumnInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Datatype             string   `protobuf:"bytes,2,opt,name=datatype,proto3" json:"datatype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnInfo) Reset()         { *m = ColumnInfo{} }
func (m *ColumnInfo) String() string { return proto.CompactTextString(m) }
func (*ColumnInfo) ProtoMessage()    {}
func (*ColumnInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{20}
}

func (m *ColumnInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnInfo.Unmarshal(m, b)
}
func (m *ColumnInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnInfo.Marshal(b, m, deterministic)
}
func (m *ColumnInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnInfo.Merge(m, src)
}
func (m *ColumnInfo) XXX_Size() int {
	return xxx_messageInfo_ColumnInfo.Size(m)
}
func (m *ColumnInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnInfo proto.InternalMessageInfo

func (m *ColumnInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ColumnInfo) GetDatatype() string {
	if m != nil {
		return m.Datatype
	}
	return ""
}

type ColumnResponse struct {
	// Types that are valid to be assigned to ColumnVal:
	//	*ColumnResponse_StringVal
	//	*ColumnResponse_IntVal
	//	*ColumnResponse_BoolVal
	//	*ColumnResponse_BlobVal
	ColumnVal            isColumnResponse_ColumnVal `protobuf_oneof:"columnVal"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ColumnResponse) Reset()         { *m = ColumnResponse{} }
func (m *ColumnResponse) String() string { return proto.CompactTextString(m) }
func (*ColumnResponse) ProtoMessage()    {}
func (*ColumnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a66c591da5e2e6d0, []int{21}
}

func (m *ColumnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnResponse.Unmarshal(m, b)
}
func (m *ColumnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnResponse.Marshal(b, m, deterministic)
}
func (m *ColumnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnResponse.Merge(m, src)
}
func (m *ColumnResponse) XXX_Size() int {
	return xxx_messageInfo_ColumnResponse.Size(m)
}
func (m *ColumnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnResponse proto.InternalMessageInfo

type isColumnResponse_ColumnVal interface {
	isColumnResponse_ColumnVal()
}

type ColumnResponse_StringVal struct {
	StringVal string `protobuf:"bytes,1,opt,name=stringVal,proto3,oneof"`
}

type ColumnResponse_IntVal struct {
	IntVal int64 `protobuf:"varint,2,opt,name=intVal,proto3,oneof"`
}

type ColumnResponse_BoolVal struct {
	BoolVal bool `protobuf:"varint,3,opt,name=boolVal,proto3,oneof"`
}

type ColumnResponse_BlobVal struct {
	BlobVal []byte `protobuf:"bytes,4,opt,name=blobVal,proto3,oneof"`
}

func (*ColumnResponse_StringVal) isColumnResponse_ColumnVal() {}

func (*ColumnResponse_IntVal) isColumnResponse_ColumnVal() {}

func (*ColumnResponse_BoolVal) isColumnResponse_ColumnVal() {}

func (*ColumnResponse_BlobVal) isColumnResponse_ColumnVal() {}

func (m *ColumnResponse) GetColumnVal() isColumnResponse_ColumnVal {
	if m != nil {
		return m.ColumnVal
	}
	return nil
}

func (m *ColumnResponse) GetStringVal() string {
	if x, ok := m.GetColumnVal().(*ColumnResponse_StringVal); ok {
		return x.StringVal
	}
	return ""
}

func (m *ColumnResponse) GetIntVal() int64 {
	if x, ok := m.GetColumnVal().(*ColumnResponse_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (m *ColumnResponse) GetBoolVal() bool {
	if x, ok := m.GetColumnVal().(*ColumnResponse_BoolVal); ok {
		return x.BoolVal
	}
	return false
}

func (m *ColumnResponse) GetBlobVal() []byte {
	if x, ok := m.GetColumnVal().(*ColumnResponse_BlobVal); ok {
		return x.BlobVal
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ColumnResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ColumnResponse_StringVal)(nil),
		(*ColumnResponse_IntVal)(nil),
		(*ColumnResponse_BoolVal)(nil),
		(*ColumnResponse_BlobVal)(nil),
	}
}

func init() {
	proto.RegisterType((*Row)(nil), "gopilosa_pbuf.Row")
	proto.RegisterType((*RowIdentifiers)(nil), "gopilosa_pbuf.RowIdentifiers")
	proto.RegisterType((*Pair)(nil), "gopilosa_pbuf.Pair")
	proto.RegisterType((*FieldRow)(nil), "gopilosa_pbuf.FieldRow")
	proto.RegisterType((*GroupCount)(nil), "gopilosa_pbuf.GroupCount")
	proto.RegisterType((*ValCount)(nil), "gopilosa_pbuf.ValCount")
	proto.RegisterType((*ColumnAttrSet)(nil), "gopilosa_pbuf.ColumnAttrSet")
	proto.RegisterType((*Attr)(nil), "gopilosa_pbuf.Attr")
	proto.RegisterType((*AttrMap)(nil), "gopilosa_pbuf.AttrMap")
	proto.RegisterType((*QueryRequest)(nil), "gopilosa_pbuf.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "gopilosa_pbuf.QueryResponse")
	proto.RegisterType((*QueryResult)(nil), "gopilosa_pbuf.QueryResult")
	proto.RegisterType((*ImportRequest)(nil), "gopilosa_pbuf.ImportRequest")
	proto.RegisterType((*ImportValueRequest)(nil), "gopilosa_pbuf.ImportValueRequest")
	proto.RegisterType((*TranslateKeysRequest)(nil), "gopilosa_pbuf.TranslateKeysRequest")
	proto.RegisterType((*TranslateKeysResponse)(nil), "gopilosa_pbuf.TranslateKeysResponse")
	proto.RegisterType((*ImportRoaringRequestView)(nil), "gopilosa_pbuf.ImportRoaringRequestView")
	proto.RegisterType((*ImportRoaringRequest)(nil), "gopilosa_pbuf.ImportRoaringRequest")
	proto.RegisterType((*QueryPQLRequest)(nil), "gopilosa_pbuf.QueryPQLRequest")
	proto.RegisterType((*RowResponse)(nil), "gopilosa_pbuf.RowResponse")
	proto.RegisterType((*ColumnInfo)(nil), "gopilosa_pbuf.ColumnInfo")
	proto.RegisterType((*ColumnResponse)(nil), "gopilosa_pbuf.ColumnResponse")
}

func init() { proto.RegisterFile("gopilosa_pbuf/public.proto", fileDescriptor_a66c591da5e2e6d0) }

var fileDescriptor_a66c591da5e2e6d0 = []byte{
	// 1065 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0x45, 0x4a, 0x22, 0x87, 0xb6, 0x13, 0xec, 0xef, 0x3f, 0x65, 0x04, 0xc7, 0x10, 0x88,
	0xa2, 0x55, 0x2e, 0xea, 0x16, 0x4a, 0x80, 0x9e, 0x0b, 0xd4, 0x91, 0x53, 0xab, 0x69, 0x0d, 0x7b,
	0x6d, 0xe8, 0xaa, 0x68, 0xb0, 0x92, 0xd6, 0x0e, 0x51, 0x8a, 0xcb, 0xf0, 0x50, 0xc5, 0xb7, 0x7d,
	0x81, 0x3e, 0x41, 0xef, 0x7b, 0xd1, 0x07, 0xe9, 0x6b, 0xf4, 0xba, 0x2f, 0x51, 0xec, 0xec, 0xae,
	0x48, 0xd1, 0x4a, 0x4f, 0xe8, 0xdd, 0x9c, 0x76, 0x38, 0xdf, 0xcc, 0xec, 0xb7, 0x84, 0xde, 0xb5,
	0x48, 0xa3, 0x58, 0xe4, 0xec, 0x79, 0x3a, 0x2d, 0xaf, 0xde, 0x4d, 0xcb, 0x69, 0x1c, 0xcd, 0x0e,
	0xd3, 0x4c, 0x14, 0x82, 0xec, 0xac, 0xf9, 0xc2, 0x6f, 0xc1, 0xa6, 0x62, 0x49, 0x02, 0xe8, 0x3e,
	0x11, 0x71, 0xb9, 0x48, 0xf2, 0xc0, 0xea, 0xdb, 0x03, 0x87, 0x1a, 0x95, 0x10, 0x70, 0x9e, 0xf1,
	0x9b, 0x3c, 0xb0, 0xfb, 0xf6, 0xc0, 0xa3, 0x28, 0x93, 0x87, 0xd0, 0xfe, 0xbc, 0x28, 0xb2, 0x3c,
	0x68, 0xf5, 0xed, 0x81, 0x3f, 0xfc, 0xdf, 0xe1, 0x5a, 0xce, 0x43, 0xe9, 0xa3, 0x2a, 0x22, 0xfc,
	0x00, 0x76, 0xa9, 0x58, 0x8e, 0xe7, 0x3c, 0x29, 0xa2, 0xab, 0x88, 0x67, 0x98, 0x90, 0x8a, 0xa5,
	0xf9, 0x0e, 0xca, 0xab, 0x8f, 0xb4, 0xaa, 0x8f, 0x84, 0x9f, 0x81, 0x73, 0xc6, 0xa2, 0x8c, 0xec,
	0x42, 0x6b, 0x3c, 0x0a, 0xac, 0xbe, 0x35, 0x70, 0x68, 0x6b, 0x3c, 0x22, 0x77, 0xc1, 0x7e, 0xc6,
	0x6f, 0x02, 0xbb, 0x6f, 0x0d, 0x3c, 0x2a, 0x45, 0xb2, 0x07, 0xed, 0x27, 0xa2, 0x4c, 0x8a, 0xa0,
	0x85, 0x41, 0x4a, 0x09, 0x4f, 0xc1, 0x7d, 0x1a, 0xf1, 0x78, 0x2e, 0xe1, 0xed, 0x41, 0x1b, 0x65,
	0x4c, 0xe3, 0x51, 0xa5, 0x48, 0xab, 0xac, 0x6d, 0x64, 0xce, 0xa1, 0x42, 0xee, 0x41, 0x87, 0x8a,
	0x65, 0xf5, 0x09, 0xad, 0x85, 0xe7, 0x00, 0x5f, 0x64, 0xa2, 0x4c, 0x31, 0x3b, 0x79, 0x07, 0xda,
	0xa8, 0x21, 0x0c, 0x7f, 0xf8, 0x46, 0xa3, 0x05, 0xe6, 0xcb, 0x54, 0x45, 0xbd, 0xa6, 0xc4, 0x21,
	0xb8, 0x13, 0x16, 0xab, 0x84, 0x77, 0xc1, 0x9e, 0xb0, 0x18, 0x0b, 0xb4, 0xa9, 0x14, 0xd7, 0xcf,
	0xd8, 0xe6, 0xcc, 0x37, 0xb0, 0xa3, 0x46, 0x23, 0xfb, 0x7b, 0xc1, 0x8b, 0xbf, 0xd1, 0x9f, 0x7f,
	0x30, 0xae, 0x9f, 0x2d, 0x70, 0xa4, 0x64, 0xb2, 0x58, 0x55, 0x16, 0x02, 0xce, 0xe5, 0x4d, 0xca,
	0x35, 0x02, 0x94, 0x49, 0x1f, 0xfc, 0x8b, 0x22, 0x8b, 0x92, 0xeb, 0x09, 0x8b, 0x4b, 0xae, 0xbf,
	0x59, 0x37, 0x91, 0x1e, 0xb8, 0xe3, 0xa4, 0x50, 0x6e, 0x07, 0x71, 0xac, 0x74, 0xb2, 0x0f, 0xde,
	0x91, 0x10, 0xb1, 0x72, 0xb6, 0xfb, 0xd6, 0xc0, 0xa5, 0x95, 0x81, 0x1c, 0x00, 0x3c, 0x8d, 0x05,
	0xd3, 0x67, 0x3b, 0x7d, 0x6b, 0x60, 0xd1, 0x9a, 0x25, 0x7c, 0x0c, 0x5d, 0x59, 0xe9, 0xd7, 0x2c,
	0xad, 0x00, 0x5a, 0x7f, 0x09, 0xf0, 0x57, 0x0b, 0xb6, 0xcf, 0x4b, 0x9e, 0xdd, 0x50, 0xfe, 0xb2,
	0xe4, 0x79, 0x21, 0xbb, 0x8c, 0xba, 0x59, 0x0d, 0x54, 0xe4, 0x12, 0x5c, 0xbc, 0x60, 0xd9, 0x5c,
	0xf5, 0xcc, 0xa1, 0x5a, 0x93, 0x80, 0xab, 0xee, 0xe7, 0x08, 0xd8, 0xa5, 0x75, 0x13, 0xae, 0x0f,
	0x5f, 0x88, 0xc2, 0x20, 0xd2, 0x1a, 0x19, 0xc0, 0x9d, 0xe3, 0x57, 0xb3, 0xb8, 0x9c, 0x73, 0x2a,
	0x96, 0xea, 0x74, 0x07, 0x03, 0x9a, 0x66, 0xf2, 0x16, 0xec, 0x6a, 0x93, 0xb9, 0x92, 0x5d, 0x0c,
	0x6c, 0x58, 0xc3, 0x9f, 0x2c, 0xd8, 0xd1, 0x50, 0xf2, 0x54, 0x24, 0x39, 0x97, 0x43, 0x3b, 0xce,
	0x32, 0x33, 0xb4, 0xe3, 0x2c, 0x23, 0x8f, 0xa1, 0x4b, 0x79, 0x5e, 0xc6, 0x85, 0x19, 0x7e, 0xaf,
	0xd1, 0x1b, 0x93, 0xa0, 0x8c, 0x0b, 0x6a, 0x42, 0xc9, 0x08, 0x76, 0xd7, 0x76, 0x4c, 0xdd, 0x7e,
	0x7f, 0xb8, 0xdf, 0x38, 0xbc, 0x16, 0x44, 0x1b, 0x67, 0xc2, 0xdf, 0x5b, 0xe0, 0xd7, 0xd2, 0xaf,
	0x16, 0x48, 0xc2, 0xde, 0xd1, 0x0b, 0xf4, 0x26, 0xd2, 0x0f, 0x56, 0xec, 0x0f, 0x49, 0x23, 0xbd,
	0xbc, 0x3f, 0xc8, 0x4e, 0xdb, 0x60, 0x9d, 0xea, 0xbd, 0xb3, 0x4e, 0xe5, 0xb4, 0x25, 0x31, 0x98,
	0xa2, 0x9a, 0xd3, 0x96, 0x3e, 0xaa, 0x22, 0x90, 0xd6, 0x5e, 0xb0, 0xe4, 0x9a, 0xcf, 0x71, 0xf9,
	0x5c, 0x6a, 0x54, 0xf2, 0xa8, 0xba, 0x7a, 0x38, 0xa8, 0xdb, 0x57, 0xd8, 0xb8, 0x69, 0x75, 0x47,
	0x15, 0x35, 0x8c, 0x47, 0x72, 0x22, 0xb8, 0x15, 0x4a, 0x23, 0x1f, 0x83, 0x5f, 0x51, 0x43, 0x1e,
	0xb8, 0x58, 0xd7, 0xfd, 0x46, 0xbe, 0x2a, 0x82, 0xd6, 0xa3, 0xc9, 0x71, 0x93, 0x21, 0x03, 0x0f,
	0xeb, 0x79, 0x70, 0xbb, 0x1b, 0xb5, 0x20, 0xda, 0x38, 0x14, 0xfe, 0x66, 0xc1, 0xce, 0x78, 0x91,
	0x8a, 0xac, 0xa8, 0x6d, 0xf6, 0x38, 0x99, 0xf3, 0x57, 0x66, 0xb3, 0x51, 0xa9, 0xa8, 0xb0, 0xd5,
	0xa0, 0x42, 0xdc, 0x70, 0xdc, 0x68, 0x87, 0x2a, 0xa5, 0x86, 0xd7, 0x59, 0xc3, 0xbb, 0x0f, 0x9e,
	0x9a, 0xb5, 0x74, 0xb5, 0xd1, 0x55, 0x19, 0x64, 0xd3, 0x15, 0x65, 0xaa, 0x36, 0x79, 0xd4, 0xa8,
	0xf2, 0x4a, 0xab, 0x30, 0x74, 0xba, 0xe8, 0xac, 0x59, 0xa4, 0xff, 0x32, 0x5a, 0xf0, 0xbc, 0x60,
	0x8b, 0x54, 0x5e, 0x0f, 0x7b, 0x60, 0xd3, 0x9a, 0x25, 0xfc, 0xc5, 0x02, 0xa2, 0x30, 0x22, 0x05,
	0xfc, 0x77, 0x40, 0xff, 0x1c, 0xd0, 0x7a, 0xd9, 0xdd, 0x5b, 0x65, 0xdf, 0x83, 0x0e, 0xd6, 0x63,
	0x4a, 0xd6, 0x5a, 0x38, 0x81, 0xbd, 0xcb, 0x8c, 0x25, 0x79, 0xcc, 0x0a, 0x2e, 0x03, 0xff, 0x4d,
	0xbd, 0x1b, 0x9e, 0xdf, 0xf0, 0x21, 0xfc, 0xbf, 0x91, 0xb7, 0xba, 0xff, 0x12, 0x80, 0x8d, 0x00,
	0xa4, 0x18, 0x1e, 0x41, 0xa0, 0x97, 0x42, 0x30, 0x49, 0xca, 0xba, 0x84, 0x49, 0xc4, 0x97, 0x32,
	0xf5, 0x29, 0x5b, 0x70, 0x5d, 0x05, 0xca, 0xd2, 0x36, 0x62, 0x05, 0xc3, 0x1a, 0xb6, 0x29, 0xca,
	0xe1, 0x77, 0xb0, 0xb7, 0x29, 0x07, 0xbe, 0x4f, 0x31, 0x67, 0x8a, 0x6f, 0x5c, 0xaa, 0x14, 0xf2,
	0x29, 0xb4, 0xbf, 0x8f, 0xf8, 0xd2, 0xf0, 0xcd, 0xdb, 0x8d, 0x2d, 0x7e, 0x5d, 0x35, 0x54, 0x9d,
	0x0a, 0x3f, 0x84, 0x3b, 0xc8, 0x19, 0x67, 0xe7, 0x5f, 0xd5, 0xbe, 0x13, 0xd5, 0xdb, 0x85, 0x8a,
	0xc4, 0x9a, 0xbe, 0x8c, 0x75, 0xb3, 0xa4, 0x18, 0xfe, 0x60, 0x81, 0x2f, 0x29, 0xc3, 0x74, 0xe3,
	0x23, 0xf0, 0x67, 0x38, 0xa4, 0xe7, 0x51, 0x72, 0x25, 0xf4, 0xdb, 0x70, 0x7f, 0x23, 0x85, 0x8d,
	0x93, 0x2b, 0x41, 0x61, 0xb6, 0x92, 0xc9, 0xfb, 0xd0, 0x9d, 0x69, 0xf2, 0x55, 0x38, 0x1e, 0x6c,
	0x3c, 0x67, 0xbe, 0x45, 0x4d, 0x74, 0xf8, 0x89, 0xd9, 0x15, 0x4c, 0x43, 0xc0, 0x49, 0x6a, 0x2d,
	0x96, 0xb2, 0x7c, 0x11, 0xe7, 0xac, 0x60, 0x85, 0x79, 0x4b, 0x3d, 0xba, 0xd2, 0xc3, 0x1f, 0x2d,
	0xc3, 0xbc, 0x2b, 0x14, 0x07, 0xe0, 0xe5, 0xe6, 0x3d, 0x55, 0x79, 0x4e, 0xb6, 0x68, 0x65, 0x22,
	0x01, 0x74, 0x22, 0x7c, 0x50, 0xd5, 0x6f, 0xc2, 0xc9, 0x16, 0xd5, 0x3a, 0xe9, 0x41, 0x77, 0xaa,
	0x5e, 0x53, 0xf5, 0x4e, 0x9d, 0x6c, 0x51, 0x63, 0x40, 0x5f, 0x2c, 0xa6, 0xd2, 0x27, 0x89, 0x71,
	0x1b, 0x7d, 0xca, 0x70, 0xe4, 0x83, 0xa7, 0xd0, 0x4c, 0x58, 0x3c, 0xbc, 0x84, 0xce, 0x19, 0xc2,
	0x26, 0x5f, 0x82, 0x6b, 0x26, 0x43, 0x0e, 0x36, 0xbd, 0x22, 0xd5, 0xc8, 0x7a, 0xbd, 0x0d, 0x4c,
	0xae, 0x01, 0x85, 0x5b, 0xef, 0x59, 0xd3, 0x0e, 0xfe, 0x8b, 0x3e, 0xfa, 0x23, 0x00, 0x00, 0xff,
	0xff, 0x71, 0x68, 0x41, 0xfd, 0xa9, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PilosaClient is the client API for Pilosa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PilosaClient interface {
	QueryPQL(ctx context.Context, in *QueryPQLRequest, opts ...grpc.CallOption) (Pilosa_QueryPQLClient, error)
}

type pilosaClient struct {
	cc *grpc.ClientConn
}

func NewPilosaClient(cc *grpc.ClientConn) PilosaClient {
	return &pilosaClient{cc}
}

func (c *pilosaClient) QueryPQL(ctx context.Context, in *QueryPQLRequest, opts ...grpc.CallOption) (Pilosa_QueryPQLClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Pilosa_serviceDesc.Streams[0], "/gopilosa_pbuf.Pilosa/QueryPQL", opts...)
	if err != nil {
		return nil, err
	}
	x := &pilosaQueryPQLClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Pilosa_QueryPQLClient interface {
	Recv() (*RowResponse, error)
	grpc.ClientStream
}

type pilosaQueryPQLClient struct {
	grpc.ClientStream
}

func (x *pilosaQueryPQLClient) Recv() (*RowResponse, error) {
	m := new(RowResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PilosaServer is the server API for Pilosa service.
type PilosaServer interface {
	QueryPQL(*QueryPQLRequest, Pilosa_QueryPQLServer) error
}

// UnimplementedPilosaServer can be embedded to have forward compatible implementations.
type UnimplementedPilosaServer struct {
}

func (*UnimplementedPilosaServer) QueryPQL(req *QueryPQLRequest, srv Pilosa_QueryPQLServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryPQL not implemented")
}

func RegisterPilosaServer(s *grpc.Server, srv PilosaServer) {
	s.RegisterService(&_Pilosa_serviceDesc, srv)
}

func _Pilosa_QueryPQL_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryPQLRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PilosaServer).QueryPQL(m, &pilosaQueryPQLServer{stream})
}

type Pilosa_QueryPQLServer interface {
	Send(*RowResponse) error
	grpc.ServerStream
}

type pilosaQueryPQLServer struct {
	grpc.ServerStream
}

func (x *pilosaQueryPQLServer) Send(m *RowResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Pilosa_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gopilosa_pbuf.Pilosa",
	HandlerType: (*PilosaServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryPQL",
			Handler:       _Pilosa_QueryPQL_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gopilosa_pbuf/public.proto",
}
